# Generated by Django 2.1.5 on 2021-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('Katė', 'Katė'), ('Šuo', 'Šuo'), ('Arklys', 'Arklys')], max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='animal_pics')),
            ],
        ),
    ]
